apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: my-run-demo-app-1
description: main application pipeline
serialPipeline:
  stages:
  - targetId: run-qsdev
    profiles: [dev] # This tells Cloud Deploy to use the 'dev' profile from skaffold.yaml for this stage
  - targetId: run-qsprod
    profiles: [prod] # This tells Cloud Deploy to use the 'prod' profile from skaffold.yaml for this stage
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: run-qsdev
description: Cloud Run development service
run:
  # The 'location' field for a Cloud Run target should be in the format 'projects/PROJECT_ID/locations/REGION'.
  # You've currently provided 'projects/prj-d-playground-shj9/locations/asia-southeast1'.
  # While this includes the project ID, it's more conventional and often expected
  # to just provide the region directly in the 'location' field within the 'run' block,
  # and let the 'gcloud deploy' command infer the project from your gcloud config
  # or from the --project flag.
  # However, the provided format *should* still work if that's your project ID.
  location: projects/prj-d-playground-shj9/locations/asia-southeast1

---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: run-qsprod
description: Cloud Run production service
run:
  location: projects/prj-d-playground-shj9/locations/asia-southeast1
  # You might want to add requireApproval: true for production targets
  # requireApproval: true