apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: deploy-run-service-prod
spec:
  template:
    spec:
      containers:
        - image: nginx
          ports:
            - containerPort: 80
