apiVersion: skaffold/v4beta7
kind: Config
metadata: 
  name: deploy-run-quickstart
profiles:
- name: service-1
  manifests:
    rawYaml:
    - ./services/service_1.yaml
- name: service-2
  manifests:
    rawYaml:
    - ./services/service_2.yaml
deploy:
  cloudrun: {}