apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: dev-service-1
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: 1   # Min number of instance
        autoscaling.knative.dev/maxScale: 1   # Max number of instance
    spec:
      containers:
        - image: nginx
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "256Mi"
              cpu: "1"
  traffic:
    - latestRevision: true
      percent: 100
  metadata:
    annotations:
      run.googleapis.com/cpu-throttling:  "true"        # Billing request based